USE [master]
GO
/****** Object:  Database [BankovniSistem]    Script Date: 2/3/2024 11:53:36 AM ******/
CREATE DATABASE [BankovniSistem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BankovniSistem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BankovniSistem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BankovniSistem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\BankovniSistem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [BankovniSistem] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BankovniSistem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BankovniSistem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BankovniSistem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BankovniSistem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BankovniSistem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BankovniSistem] SET ARITHABORT OFF 
GO
ALTER DATABASE [BankovniSistem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BankovniSistem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BankovniSistem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BankovniSistem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BankovniSistem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BankovniSistem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BankovniSistem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BankovniSistem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BankovniSistem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BankovniSistem] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BankovniSistem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BankovniSistem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BankovniSistem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BankovniSistem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BankovniSistem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BankovniSistem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BankovniSistem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BankovniSistem] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BankovniSistem] SET  MULTI_USER 
GO
ALTER DATABASE [BankovniSistem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BankovniSistem] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BankovniSistem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BankovniSistem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BankovniSistem] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BankovniSistem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [BankovniSistem] SET QUERY_STORE = ON
GO
ALTER DATABASE [BankovniSistem] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [BankovniSistem]
GO
/****** Object:  Table [dbo].[CashDeposit]    Script Date: 2/3/2024 11:53:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CashDeposit](
	[TransactionID] [int] NOT NULL,
	[AccountID] [int] NOT NULL,
 CONSTRAINT [PK__CashDepo__55433A4B8778D16B] PRIMARY KEY CLUSTERED 
(
	[TransactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CashWithdrawal]    Script Date: 2/3/2024 11:53:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CashWithdrawal](
	[TransactionID] [int] NOT NULL,
	[AccountID] [int] NOT NULL,
 CONSTRAINT [PK__CashWith__55433A4B3311EC3E] PRIMARY KEY CLUSTERED 
(
	[TransactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblAccount]    Script Date: 2/3/2024 11:53:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblAccount](
	[AccID] [int] IDENTITY(1,1) NOT NULL,
	[AccNum] [int] NOT NULL,
	[AccBal] [float] NOT NULL,
	[AccDate] [datetime] NULL,
	[ClientID] [int] NOT NULL,
 CONSTRAINT [PK_TblAccount] PRIMARY KEY CLUSTERED 
(
	[AccID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblCard]    Script Date: 2/3/2024 11:53:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblCard](
	[CardNum] [nvarchar](25) NOT NULL,
	[CardHolder] [nvarchar](30) NOT NULL,
	[ExpDate] [date] NOT NULL,
	[CVV] [nvarchar](4) NOT NULL,
	[CardType] [nvarchar](10) NULL,
	[PIN] [nchar](4) NOT NULL,
	[AccID] [int] NOT NULL,
 CONSTRAINT [PK_TblCard] PRIMARY KEY CLUSTERED 
(
	[CardNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblClient]    Script Date: 2/3/2024 11:53:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblClient](
	[ClientID] [int] IDENTITY(1,1) NOT NULL,
	[ClientName] [nvarchar](15) NOT NULL,
	[ClientSname] [nvarchar](20) NOT NULL,
	[ClientJMBG] [nvarchar](50) NOT NULL,
	[DateBirth] [date] NOT NULL,
	[Sex] [char](1) NULL,
	[Adress] [nvarchar](30) NULL,
	[Telefon] [nvarchar](15) NULL,
	[Email] [nvarchar](30) NULL,
 CONSTRAINT [PK_TblClient] PRIMARY KEY CLUSTERED 
(
	[ClientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblEmploye]    Script Date: 2/3/2024 11:53:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblEmploye](
	[EmployeID] [int] IDENTITY(1,1) NOT NULL,
	[EmployeName] [nvarchar](15) NOT NULL,
	[EmployeSurn] [nvarchar](15) NOT NULL,
	[EmployeJMBG] [nvarchar](50) NOT NULL,
	[EmployeEmail] [nvarchar](30) NOT NULL,
	[Position] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_TblEmploye] PRIMARY KEY CLUSTERED 
(
	[EmployeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TblServices]    Script Date: 2/3/2024 11:53:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TblServices](
	[TransactionID] [int] IDENTITY(1,1) NOT NULL,
	[TransactionDate] [datetime] NOT NULL,
	[Amount] [decimal](10, 2) NOT NULL,
	[PayerName] [varchar](100) NOT NULL,
	[EmployeeID] [int] NOT NULL,
 CONSTRAINT [PK__TblServi__55433A4BE6C0C619] PRIMARY KEY CLUSTERED 
(
	[TransactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Transfer]    Script Date: 2/3/2024 11:53:36 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Transfer](
	[TransactionID] [int] NOT NULL,
	[AccountID] [int] NOT NULL,
	[ToAccountID] [int] NOT NULL,
	[CallNumber] [int] NOT NULL,
 CONSTRAINT [PK__Transfer__55433A4B14F3E12D] PRIMARY KEY CLUSTERED 
(
	[TransactionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CashDeposit]  WITH NOCHECK ADD  CONSTRAINT [FK__CashDepos__Accou__4D94879B] FOREIGN KEY([AccountID])
REFERENCES [dbo].[TblAccount] ([AccID])
GO
ALTER TABLE [dbo].[CashDeposit] CHECK CONSTRAINT [FK__CashDepos__Accou__4D94879B]
GO
ALTER TABLE [dbo].[CashDeposit]  WITH NOCHECK ADD  CONSTRAINT [FK__CashDepos__Trans__4E88ABD4] FOREIGN KEY([TransactionID])
REFERENCES [dbo].[TblServices] ([TransactionID])
GO
ALTER TABLE [dbo].[CashDeposit] CHECK CONSTRAINT [FK__CashDepos__Trans__4E88ABD4]
GO
ALTER TABLE [dbo].[CashWithdrawal]  WITH NOCHECK ADD  CONSTRAINT [FK__CashWithd__Accou__5165187F] FOREIGN KEY([AccountID])
REFERENCES [dbo].[TblAccount] ([AccID])
GO
ALTER TABLE [dbo].[CashWithdrawal] CHECK CONSTRAINT [FK__CashWithd__Accou__5165187F]
GO
ALTER TABLE [dbo].[CashWithdrawal]  WITH NOCHECK ADD  CONSTRAINT [FK__CashWithd__Trans__52593CB8] FOREIGN KEY([TransactionID])
REFERENCES [dbo].[TblServices] ([TransactionID])
GO
ALTER TABLE [dbo].[CashWithdrawal] CHECK CONSTRAINT [FK__CashWithd__Trans__52593CB8]
GO
ALTER TABLE [dbo].[TblAccount]  WITH NOCHECK ADD  CONSTRAINT [FK_TblAccount_TblClient] FOREIGN KEY([ClientID])
REFERENCES [dbo].[TblClient] ([ClientID])
GO
ALTER TABLE [dbo].[TblAccount] CHECK CONSTRAINT [FK_TblAccount_TblClient]
GO
ALTER TABLE [dbo].[TblCard]  WITH NOCHECK ADD  CONSTRAINT [FK_TblCard_TblAccount] FOREIGN KEY([AccID])
REFERENCES [dbo].[TblAccount] ([AccID])
GO
ALTER TABLE [dbo].[TblCard] CHECK CONSTRAINT [FK_TblCard_TblAccount]
GO
ALTER TABLE [dbo].[TblServices]  WITH NOCHECK ADD  CONSTRAINT [FK__TblServic__Emplo__47DBAE45] FOREIGN KEY([EmployeeID])
REFERENCES [dbo].[TblEmploye] ([EmployeID])
GO
ALTER TABLE [dbo].[TblServices] CHECK CONSTRAINT [FK__TblServic__Emplo__47DBAE45]
GO
ALTER TABLE [dbo].[Transfer]  WITH NOCHECK ADD  CONSTRAINT [FK__Transfer__FromAc__5535A963] FOREIGN KEY([AccountID])
REFERENCES [dbo].[TblAccount] ([AccID])
GO
ALTER TABLE [dbo].[Transfer] CHECK CONSTRAINT [FK__Transfer__FromAc__5535A963]
GO
ALTER TABLE [dbo].[Transfer]  WITH NOCHECK ADD  CONSTRAINT [FK__Transfer__Transa__571DF1D5] FOREIGN KEY([TransactionID])
REFERENCES [dbo].[TblServices] ([TransactionID])
GO
ALTER TABLE [dbo].[Transfer] CHECK CONSTRAINT [FK__Transfer__Transa__571DF1D5]
GO
USE [master]
GO
ALTER DATABASE [BankovniSistem] SET  READ_WRITE 
GO
